Algoritmo "DESAFIO2"

Var
num1,num2,num3,num4,quadrado1,quadrado2,quadrado3,quadrado4,soma: real

Inicio
escreval("Digite 4 números:")
leia(num1)
leia(num2)
leia(num3)
leia(num4)

quadrado1 <- num1 * num1
quadrado2 <- num2 * num2
quadrado3 <- num3 * num3
quadrado4 <- num4 * num4

soma <- quadrado1 + quadrado2 + quadrado3 + quadrado4

escreval("A soma dos quadrados dso números é igual a",soma,"")

Fimalgoritmo