Algoritmo "maiorQue18"
// Disciplina   : Programação e algoritmos
// Professor   : Edilma Bindá
// Autor(a)    : Paulo Augusto Costa
// Data atual  : 25/05/2023

Var
idade: real


Inicio
escreval("Começou!")
escreval("Qual a sua idade?")
leia(idade)

se idade >= 18 entao
escreval("OK, pode passar!")
senao
escreval("Você não pode passar!")
fimse

escreval("Acabou!")


Fimalgoritmo